ALL_COUNTRIES_DATA = [
    ("AF", "Afghanistan (+93)", "🇦🇫"),
    ("AL", "Albania (+355)", "🇦🇱"),
    ("DZ", "Algeria (+213)", "🇩🇿"),
    ("AI", "Anguilla (+1)", "🇦🇮"),
    ("AO", "Angola (+244)", "🇦🇴"),
    ("AR", "Argentina (+54)", "🇦🇷"),
    ("AM", "Armenia (+374)", "🇦🇲"),
    ("AW", "Aruba (+297)", "🇦🇼"),
    ("AU", "Australia (+61)", "🇦🇺"),
    ("AT", "Austria (+43)", "🇦🇹"),
    ("AZ", "Azerbaijan (+994)", "🇦🇿"),
    ("BS", "Bahamas (+1)", "🇧🇸"),
    ("BH", "Bahrain (+973)", "🇧🇭"),
    ("BD", "Bangladesh (+880)", "🇧🇩"),
    ("BB", "Barbados (+1)", "🇧🇧"),
    ("BY", "Belarus (+375)", "🇧🇾"),
    ("BE", "Belgium (+32)", "🇧🇪"),
    ("BZ", "Belize (+501)", "🇧🇿"),
    ("BJ", "Benin (+229)", "🇧🇯"),
    ("BM", "Bermuda (+14)", "🇧🇲"),
    ("BT", "Bhutan (+975)", "🇧🇹"),
    ("BO", "Bolivia (+591)", "🇧🇴"),
    ("BA", "Bosnia and Herzegovina (+387)", "🇧🇦"),
    ("BW", "Botswana (+267)", "🇧🇼"),
    ("BR", "Brazil (+55)", "🇧🇷"),
    ("BG", "Bulgaria (+359)", "🇧🇬"),
    ("BI", "Burundi (+257)", "🇧🇮"),
    ("KH", "Cambodia (+855)", "🇰🇭"),
    ("CM", "Cameroon (+237)", "🇨🇲"),
    ("CA", "Canada (+1)", "🇨🇦"),
    ("CV", "Cape Verde (+238)", "🇨🇻"),
    ("KY", "Cayman Islands (+1)", "🇰🇾"),
    ("CF", "Central African Republic (+236)", "🇨🇫"),
    ("TD", "Chad (+235)", "🇹🇩"),
    ("CL", "Chile (+56)", "🇨🇱"),
    ("CN", "China (+86)", "🇨🇳"),
    ("CO", "Colombia (+57)", "🇨🇴"),
    ("KM", "Comoros (+269)", "🇰🇲"),
    ("CG", "Congo (+242)", "🇨🇬"),
    ("CR", "Costa Rica (+506)", "🇨🇷"),
    ("CI", "Côte d'Ivoire (+225)", "🇨🇮"),
    ("HR", "Croatia (+385)", "🇭🇷"),
    ("CU", "Cuba (+53)", "🇨🇺"),
    ("CZ", "Czech Republic (+420)", "🇨🇿"),
    ("DK", "Denmark (+45)", "🇩🇰"),
    ("DJ", "Djibouti (+253)", "🇩🇯"),
    ("DM", "Dominica (+1)", "🇩🇲"),
    ("DO", "Dominican Republic (+1)", "🇩🇴"),
    ("EC", "Ecuador (+593)", "🇪🇨"),
    ("EG", "Egypt (+20)", "🇪🇬"),
    ("SV", "El Salvador (+503)", "🇸🇻"),
    ("EE", "Estonia (+372)", "🇪🇪"),
    ("ET", "Ethiopia (+251)", "🇪🇹"),
    ("FK", "Falkland Islands (+500)", "🇫🇰"),
    ("FJ", "Fiji (+679)", "🇫🇯"),
    ("FI", "Finland (+358)", "🇫🇮"),
    ("FR", "France (+33)", "🇫🇷"),
    ("GA", "Gabon (+241)", "🇬🇦"),
    ("GE", "Georgia (+995)", "🇬🇪"),
    ("DE", "Germany (+49)", "🇩🇪"),
    ("GH", "Ghana (+233)", "🇬🇭"),
    ("GR", "Greece (+30)", "🇬🇷"),
    ("GL", "Greenland (+299)", "🇬🇱"),
    ("GD", "Grenada (+1)", "🇬🇩"),
    ("GP", "Guadeloupe (+590)", "🇬🇵"),
    ("GU", "Guam (+1)", "🇬🇺"),
    ("GT", "Guatemala (+502)", "🇬🇹"),
    ("GN", "Guinea (+224)", "🇬🇳"),
    ("GY", "Guyana (+592)", "🇬🇾"),
    ("HT", "Haiti (+509)", "🇭🇹"),
    ("HN", "Honduras (+504)", "🇭🇳"),
    ("HK", "Hong Kong (+852)", "🇭🇰"),
    ("HU", "Hungary (+36)", "🇭🇺"),
    ("IS", "Iceland (+354)", "🇮🇸"),
    ("IN", "India (+91)", "🇮🇳"),
    ("ID", "Indonesia (+62)", "🇮🇩"),
    ("IR", "Iran (+98)", "🇮🇷"),
    ("IQ", "Iraq (+964)", "🇮🇶"),
    ("IE", "Ireland (+353)", "🇮🇪"),
    ("IL", "Israel (+972)", "🇮🇱"),
    ("IT", "Italy (+39)", "🇮🇹"),
    ("JM", "Jamaica (+1)", "🇯🇲"),
    ("JP", "Japan (+81)", "🇯🇵"),
    ("JO", "Jordan (+962)", "🇯🇴"),
    ("KZ", "Kazakhstan (+7)", "🇰🇿"),
    ("KE", "Kenya (+254)", "🇰🇪"),
    ("KI", "Kiribati (+686)", "🇰🇮"),
    ("KW", "Kuwait (+965)", "🇰🇼"),
    ("KG", "Kyrgyzstan (+996)", "🇰🇬"),
    ("LA", "Laos (+856)", "🇱🇦"),
    ("LB", "Lebanon (+961)", "🇱🇧"),
    ("LS", "Lesotho (+266)", "🇱🇸"),
    ("LY", "Libya (+218)", "🇱🇾"),
    ("LT", "Lithuania (+370)", "🇱🇹"),
    ("LU", "Luxembourg (+352)", "🇱🇺"),
    ("MO", "Macao (+853)", "🇲🇴"),
    ("MG", "Madagascar (+261)", "🇲🇬"),
    ("MW", "Malawi (+265)", "🇲🇼"),
    ("MY", "Malaysia (+60)", "🇲🇾"),
    ("MV", "Maldives (+960)", "🇲🇻"),
    ("ML", "Mali (+223)", "🇲🇱"),
    ("MT", "Malta (+356)", "🇲🇹"),
    ("MQ", "Martinique (+596)", "🇲🇶"),
    ("MR", "Mauritania (+222)", "🇲🇷"),
    ("MU", "Mauritius (+230)", "🇲🇺"),
    ("MX", "Mexico (+52)", "🇲🇽"),
    ("MD", "Moldova (+373)", "🇲🇩"),
    ("MC", "Monaco (+377)", "🇲🇨"),
    ("MN", "Mongolia (+976)", "🇲🇳"),
    ("MA", "Morocco (+212)", "🇲🇦"),
    ("MZ", "Mozambique (+258)", "🇲🇿"),
    ("MM", "Myanmar (+95)", "🇲🇲"),
    ("NA", "Namibia (+264)", "🇳🇦"),
    ("NP", "Nepal (+977)", "🇳🇵"),
    ("NL", "Netherlands (+31)", "🇳🇱"),
    ("NZ", "New Zealand (+64)", "🇳🇿"),
    ("NI", "Nicaragua (+505)", "🇳🇮"),
    ("NE", "Niger (+227)", "🇳🇪"),
    ("NG", "Nigeria (+234)", "🇳🇬"),
    ("NU", "Niue (+683)", "🇳🇺"),
    ("NO", "Norway (+47)", "🇳🇴"),
    ("OM", "Oman (+968)", "🇴🇲"),
    ("PK", "Pakistan (+92)", "🇵🇰"),
    ("PS", "Palestine (+970)", "🇵🇸"),
    ("PA", "Panama (+507)", "🇵🇦"),
    ("PG", "Papua New Guinea (+675)", "🇵🇬"),
    ("PY", "Paraguay (+595)", "🇵🇾"),
    ("PE", "Peru (+51)", "🇵🇪"),
    ("PH", "Philippines (+63)", "🇵🇭"),
    ("PL", "Poland (+48)", "🇵🇱"),
    ("PT", "Portugal (+351)", "🇵🇹"),
    ("PR", "Puerto Rico (+1787)", "🇵🇷"),
    ("QA", "Qatar (+974)", "🇶🇦"),
    ("RO", "Romania (+40)", "🇷🇴"),
    ("RU", "Russia (+7)", "🇷🇺"),
    ("ST", "São Tomé & Príncipe (+239)", "🇸🇹"),
    ("SA", "Saudi Arabia (+966)", "🇸🇦"),
    ("SN", "Senegal (+221)", "🇸🇳"),
    ("RS", "Serbia (+381)", "🇷🇸"),
    ("SC", "Seychelles (+248)", "🇸🇨"),
    ("SL", "Sierra Leone (+232)", "🇸🇱"),
    ("SG", "Singapore (+65)", "🇸🇬"),
    ("SI", "Slovenia (+386)", "🇸🇮"),
    ("SB", "Solomon Islands (+677)", "🇸🇧"),
    ("SO", "Somalia (+252)", "🇸🇴"),
    ("ZA", "South Africa (+27)", "🇿🇦"),
    ("KR", "South Korea (+82)", "🇰🇷"),
    ("SS", "South Sudan (+211)", "🇸🇸"),
    ("ES", "Spain (+34)", "🇪🇸"),
    ("LK", "Sri Lanka (+94)", "🇱🇰"),
    ("SD", "Sudan (+249)", "🇸🇩"),
    ("SR", "Suriname (+597)", "🇸🇷"),
    ("SZ", "Eswatini/Swaziland (+268)", "🇸🇿"),
    ("SE", "Sweden (+46)", "🇸🇪"),
    ("CH", "Switzerland (+41)", "🇨🇭"),
    ("SY", "Syria (+963)", "🇸🇾"),
    ("TW", "Taiwan (+886)", "🇹🇼"),
    ("TJ", "Tajikistan (+992)", "🇹🇯"),
    ("TZ", "Tanzania (+255)", "🇹🇿"),
    ("TH", "Thailand (+66)", "🇹🇭"),
    ("TL", "Timor-Leste (+670)", "🇹🇱"),
    ("TG", "Togo (+228)", "🇹🇬"),
    ("TO", "Tonga (+676)", "🇹🇴"),
    ("TT", "Trinidad and Tobago (+1)", "🇹🇹"),
    ("TN", "Tunisia (+216)", "🇹🇳"),
    ("TR", "Turkey (+90)", "🇹🇷"),
    ("TM", "Turkmenistan (+993)", "🇹🇲"),
    ("UG", "Uganda (+256)", "🇺🇬"),
    ("UA", "Ukraine (+380)", "🇺🇦"),
    ("AE", "United Arab Emirates (+971)", "🇦🇪"),
    ("GB", "United Kingdom (+44)", "🇬🇧"),
    ("US", "United States (+1)", "🇺🇸"),
    ("UY", "Uruguay (+598)", "🇺🇾"),
    ("UZ", "Uzbekistan (+998)", "🇺🇿"),
    ("VE", "Venezuela (+58)", "🇻🇪"),
    ("VN", "Vietnam (+84)", "🇻🇳"),
    ("VC", "St. Vincent & Grenadines (+1)", "🇻🇨"),
    ("WS", "Samoa (+685)", "🇼🇸"),
    ("YE", "Yemen (+967)", "🇾🇪"),
    ("ZM", "Zambia (+260)", "🇿🇲"),
    ("ZW", "Zimbabwe (+263)", "🇿🇼"),
]
